### ISSUE TITLE
PIP module still thycotic

### ISSUE THREAD

**Issue by sami1979** [DelineaXPM/python-tss-sdk#6] opened 2022-07-28 21:08 UTC
**PIP module still thycotic**

After installing through pip with version python-tss-sdk 1.1.0, the import "from delinea.secrets.server import PasswordGrantAuthorizer" fails. It is still thycotic "from thycotic.secrets.server import PasswordGrantAuthorizer"

**Expected behavior**

"from delinea.secrets.server import PasswordGrantAuthorizer" should be working

**Actual behavior**

"from thycotic.secrets.server import PasswordGrantAuthorizer" is needed for import

**Your environment**

Windows 10, Python 3.10.4, python-tss-sdk 1.1.0

**Steps to reproduce**

Install python -m pip install python-tss-sdk and try to import 
from delinea.secrets.server import PasswordGrantAuthorizer

**Comment by tylerezimmerman** [comment] 2022-08-22 19:44
@sami1979 can you please verify that the issue is resolved in the Release v1.2.0?

**Comment by tylerezimmerman** [comment] 2022-08-24 18:33
Closing until we get more feedback.

**Closed by tylerezimmerman** 2022-08-24 18:33 UTC
Labels: bug
